services:
  qbittorrent:
    container_name: qbittorrent
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Shanghai
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - ./data/qb/config:/config
      - ./data/qb/downloads:/downloads
    image: ghcr.io/hotio/qbittorrent
